
## 工艺信息表
CREATE TABLE product_process (
	id INT PRIMARY KEY IDENTITY ( 1, 1 ),
	u9_coding VARCHAR ( 64 ) DEFAULT NULL,
	product_model VARCHAR ( 255 ) DEFAULT NULL,
	customer VARCHAR ( 64 ) DEFAULT NULL,
	version VARCHAR ( 64 ) DEFAULT NULL,
	file_coding VARCHAR ( 64 ) DEFAULT NULL,
	issue_coding VARCHAR ( 64 ) DEFAULT NULL,
	issue_date datetime NULL DEFAULT NULL,
	update_date datetime NULL DEFAULT NULL,
	spraying_color VARCHAR ( 64 ) DEFAULT NULL,
	steel_seal VARCHAR ( 64 ) DEFAULT NULL,
	move_seal VARCHAR ( 64 ) DEFAULT NULL,
	pof_plastic_products VARCHAR ( 64 ) DEFAULT NULL,
	box_plastic VARCHAR ( 64 ) DEFAULT NULL,
	case_plastic VARCHAR ( 64 ) DEFAULT NULL,
	box1_label VARCHAR ( 64 ) DEFAULT NULL,
	box1_num INT DEFAULT NULL,
	box2_label VARCHAR ( 64 ) DEFAULT NULL,
	box2_num INT DEFAULT NULL,
	case1_label VARCHAR ( 64 ) DEFAULT NULL,
	case1_num INT DEFAULT NULL,
	case2_label VARCHAR ( 64 ) DEFAULT NULL,
	case2_num INT DEFAULT NULL,
	instructions text DEFAULT NULL,
	qualified_certificate VARCHAR ( 255 ) DEFAULT NULL,
	sealing_paste VARCHAR ( 64 ) DEFAULT NULL,
	packaging_tape VARCHAR ( 64 ) DEFAULT NULL,
	packaging_tape_number INT DEFAULT NULL,
	sealing_gummed_paper VARCHAR ( 64 ) DEFAULT NULL,
	process1_picture_name VARCHAR ( 64 ) DEFAULT NULL,
	process2_picture_name VARCHAR ( 64 ) DEFAULT NULL,
	process3_picture_name VARCHAR ( 64 ) DEFAULT NULL,
	process4_picture_name VARCHAR ( 64 ) DEFAULT NULL,
	shell_fabric VARCHAR ( 64 ) DEFAULT NULL,
	bed_charge VARCHAR ( 64 ) DEFAULT NULL,
	box_number VARCHAR ( 64 ) DEFAULT NULL,
	case_number VARCHAR ( 64 ) DEFAULT NULL,
	child_thing_number VARCHAR ( 64 ) DEFAULT NULL,
	crt_time datetime DEFAULT NULL,
	crt_user VARCHAR ( 255 ) DEFAULT NULL,
	crt_name VARCHAR ( 255 ) DEFAULT NULL,
	crt_host VARCHAR ( 255 ) DEFAULT NULL,
	upd_time datetime DEFAULT NULL,
	upd_user VARCHAR ( 255 ) DEFAULT NULL,
	upd_name VARCHAR ( 255 ) DEFAULT NULL,
upd_host VARCHAR ( 255 ) DEFAULT NULL
)